apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: smb-flexvol-installer
  namespace: kube-system
  labels:
    k8s-app: smb
spec:
  selector:
    matchLabels:
      name: smb
  template:
    metadata:
      labels:
        name: smb
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      imagePullSecrets:
        - name: imsecret
      containers:
      - name: smb-flexvol-installer
        image: de.icr.io/im_factory/smb-flexvolume:4
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: volplugins
          mountPath: /etc/kubernetes/volumeplugins/
        - name: varlog
          mountPath: /var/log/
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/
      - name: volplugins
        hostPath:
          path: /etc/kubernetes/volumeplugins/
          type: DirectoryOrCreate
      nodeSelector:
        beta.kubernetes.io/os: linux
